### ISSUE TITLE
range that goes back more than a year only includes data going back exactly a year

### ISSUE THREAD

**Issue by ArthurZey** [andrewzey/mfp#23] opened 2015-09-25 00:22 UTC
Requested range: 2014-09-15 to 2015-09-24.
Result range: 2014-09-24 to 2015-09-24, even though the filename is `mfp-data.2014-09-15.2015-09-24.csv`.

```
$ head mfp-data.2014-09-15.2015-09-24.csv
date,calories,carbs,fat,protein,cholesterol,sodium,sugar,fiber
2014-09-24,2495,260,81,174,314,418,57,7
2014-09-25,2093,51,130,177,469,2454,6,8
2014-09-26,2495,260,81,174,314,418,57,7
2014-09-27,2145,44,134,179,2103,2831,8,0
2014-09-28,2175,49,137,177,1723,2849,7,3
2014-09-29,3620,507,81,196,314,418,57,7
2014-09-30,2093,51,130,177,469,2454,6,8
2014-10-01,2495,260,81,174,314,418,57,7
2014-10-02,2093,51,130,177,469,2454,6,8
```

**Comment by andrewzey** [comment] 2015-09-26 03:10
Dupe of #10

**Closed by andrewzey** 2015-09-26 03:10 UTC
